### ISSUE TITLE
Package resolve error => default workspace and no modding helpers

### ISSUE THREAD

**Issue by devocalypse** [hooh-hooah/ModdingTool#11]
When I try to load a fresh copy of modding-tool-060 into unity (without anything from old versions) - it gives me this error when initializing:
![image](https://user-images.githubusercontent.com/19911936/114698980-63969e00-9d28-11eb-992f-5885c6c8bf5d.png)

If I choose to continue I get the default unity workspace without any modding tool features.
Error log reads:
```
An error occurred while resolving packages:
  Package com.domybest.mybox@https://github.com/Deadcows/MyBox.git has invalid dependencies:
    com.unity.ugui: Package [com.unity.ugui@1.0.0] cannot be found
A meta data file (.meta) exists but its asset 'Assets/Plugins/Editor' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
Removing Assets/Plugins/Editor because the asset does not exist
Library\PackageCache\com.domybest.mybox@b90e45e07591f465004f33f53bdb62ffabab6efe\Tools\Internal\MyBoxWindow.cs(125,21): error CS1501: No overload for method 'Space' takes 1 arguments
Library\PackageCache\com.domybest.mybox@b90e45e07591f465004f33f53bdb62ffabab6efe\Tools\Internal\MyBoxWindow.cs(132,21): error CS1501: No overload for method 'Space' takes 1 arguments
Library\PackageCache\com.domybest.mybox@b90e45e07591f465004f33f53bdb62ffabab6efe\Tools\Internal\MyBoxWindow.cs(139,21): error CS1501: No overload for method 'Space' takes 1 arguments
Library\PackageCache\com.domybest.mybox@b90e45e07591f465004f33f53bdb62ffabab6efe\Tools\Internal\MyBoxWindow.cs(146,21): error CS1501: No overload for method 'Space' takes 1 arguments
```

**Comment by Imte06** [comment]
(using deepl translate)
(I'm new to Github, so please forgive me if I'm being rude in any way.)

Hi devocalypse.

I am not a developer, but I have found a solution to this problem.
The cause of this problem is that "Mybox.git" requires "com.unity.ugui", so I will fix that.
Solution
1) Replace the third line of "ModdingTool-release/Packages/manifest.json" with "com.domybest.mybox": "1.5.1".
2) Download this version from https://github.com/Deadcows/MyBox/releases/tag/1.5.1 and extract it.
3) Rename the file "unzipped in (2) (MyBox-1.5.1)" to "com.domybest.mybox".
4) Copy "com.domybest.mybox" to "(Unity2018.4.11f directory)\Editor\Data\Resources\PackageManager\BuiltInPackages".
(5) Open it and you should be able to open it without errors.

Hope this helps!

**Comment by devocalypse** [comment]
Thanks for taking time to share this, I appreciate it.
However it's not MyBox-1.5.1 that cannot be loaded, rather it's a dependency inside it - to com.unity.ugui which from what I understand is a part of unity itself but seems to have been deprecated and won't support 2018.4.11.f.1 anymore.

**Comment by MrKeeney81** [comment]
Thank you @Imte06I had the same problem as @devocalypse had and your solution fixed my problem

**Comment by devocalypse** [comment]
@MrKeeney81 I'm afraid installing Unity 2019.4.24 is the only way to go for this project to load properly. Keep in mind that this is not the recommended version to make mods in as it's higher than the one the games (KK and HS2) were made in. I mostly dabble in studio ports and for those it works.

**Comment by kingcc** [comment]
Thank you @Imte06 , you are so cute

**Comment by MrKeeney81** [comment]
here is how to properly fix it instead of using release use master Hooh fixed it but not in release only in master use that version it I had to clean my hard drive of unwanted file I no longer need and I deleted and I checked the master version and it had a update I read what the update was and it was a fix to this

**Comment by hooh-hooah** [comment]
#12 will solve this one
